import {defineTheme} from '@astryxdesign/core/theme';

export const MatchaTheme = defineTheme({
  name: 'Matcha',
  tokens: {
    '--color-accent': 'light-dark(#3E481D, #C0CBA9)',
    '--color-accent-muted': 'light-dark(#3E481D14, #C0CBA920)',
    '--color-on-accent': 'light-dark(#FFFFFF, #3E481D)',
    '--color-neutral': 'light-dark(#3E481D0F, #C0CBA91A)',
    '--color-background-surface': 'light-dark(#FFFFFF, #1a1c14)',
    '--color-background-body': 'light-dark(#F0F0E0, #12140e)',
    '--color-overlay': 'light-dark(#3E481D80, #3E481DCC)',
    '--color-overlay-hover': 'light-dark(#3E481D0D, #C0CBA90D)',
    '--color-overlay-pressed': 'light-dark(#3E481D1A, #C0CBA91A)',
    '--color-background-muted': 'light-dark(#F0F0E0, #3E481D)',
    '--color-text-primary': 'light-dark(#3E481D, #C0CBA9)',
    '--color-text-secondary': 'light-dark(#707E46, #94a468)',
    '--color-text-disabled': 'light-dark(#C0CBA9, #5a6440)',
    '--color-text-accent': 'light-dark(#3E481D, #C0CBA9)',
    '--color-on-dark': '#FFFFFF',
    '--color-on-light': '#3E481D',
    '--color-icon-accent': 'light-dark(#3E481D, #C0CBA9)',
    '--color-icon-primary': 'light-dark(#3E481D, #C0CBA9)',
    '--color-icon-secondary': 'light-dark(#707E46, #94a468)',
    '--color-icon-disabled': 'light-dark(#C0CBA9, #5a6440)',
    '--color-background-card': 'light-dark(#FFFFFF, #1e2016)',
    '--color-background-popover': 'light-dark(#FFFFFF, #3E481D)',
    '--color-background-inverted': 'light-dark(#3E481D, #C0CBA9)',
    '--color-success': 'light-dark(#4D9900, #6dbf2a)',
    '--color-success-muted': 'light-dark(#4D990020, #6dbf2a20)',
    '--color-on-success': 'light-dark(#FFFFFF, #3E481D)',
    '--color-error': 'light-dark(#FD0000, #ff5c5c)',
    '--color-error-muted': 'light-dark(#FD000020, #ff5c5c20)',
    '--color-on-error': 'light-dark(#FFFFFF, #3E481D)',
    '--color-warning': 'light-dark(#FFB600, #ffc940)',
    '--color-warning-muted': 'light-dark(#FFB60020, #ffc94020)',
    '--color-on-warning': 'light-dark(#3E481D, #3E481D)',
    '--color-border': 'light-dark(#DCE3CE, #C0CBA91A)',
    '--color-border-emphasized': 'light-dark(#B7C29E, #5a6440)',
    '--color-skeleton': 'light-dark(#C0CBA9, #5a6440)',
    '--color-shadow': 'light-dark(#3E481D1A, #0000004D)',
    '--color-background-blue': 'light-dark(#3a5e8c33, #3a5e8c33)',
    '--color-border-blue': 'light-dark(#3a5e8c, #7ba8d4)',
    '--color-icon-blue': 'light-dark(#3a5e8c, #7ba8d4)',
    '--color-text-blue': 'light-dark(#2e4a6e, #8dbce0)',
    '--color-background-cyan': 'light-dark(#3a7c7c33, #3a7c7c33)',
    '--color-border-cyan': 'light-dark(#3a7c7c, #70c4c4)',
    '--color-icon-cyan': 'light-dark(#3a7c7c, #70c4c4)',
    '--color-text-cyan': 'light-dark(#2e6060, #82d4d4)',
    '--color-background-gray': 'light-dark(#707E4633, #5a644033)',
    '--color-border-gray': 'light-dark(#707E46, #707E46)',
    '--color-icon-gray': 'light-dark(#707E46, #94a468)',
    '--color-text-gray': 'light-dark(#3E481D, #C0CBA9)',
    '--color-background-green': 'light-dark(#4D990033, #6dbf2a33)',
    '--color-border-green': 'light-dark(#4D9900, #6dbf2a)',
    '--color-icon-green': 'light-dark(#4D9900, #6dbf2a)',
    '--color-text-green': 'light-dark(#3d7a00, #80d43a)',
    '--color-background-orange': 'light-dark(#c4762033, #d4903a33)',
    '--color-border-orange': 'light-dark(#c47620, #d4903a)',
    '--color-icon-orange': 'light-dark(#c47620, #d4903a)',
    '--color-text-orange': 'light-dark(#a06018, #e0a04a)',
    '--color-background-pink': 'light-dark(#c44a7033, #e07a9a33)',
    '--color-border-pink': 'light-dark(#c44a70, #e07a9a)',
    '--color-icon-pink': 'light-dark(#c44a70, #e07a9a)',
    '--color-text-pink': 'light-dark(#a03a5a, #f08aaa)',
    '--color-background-purple': 'light-dark(#6b4a8c33, #b08ed433)',
    '--color-border-purple': 'light-dark(#6b4a8c, #b08ed4)',
    '--color-icon-purple': 'light-dark(#6b4a8c, #b08ed4)',
    '--color-text-purple': 'light-dark(#553a70, #c0a0e0)',
    '--color-background-red': 'light-dark(#FD000033, #ff5c5c33)',
    '--color-border-red': 'light-dark(#FD0000, #ff5c5c)',
    '--color-icon-red': 'light-dark(#FD0000, #ff5c5c)',
    '--color-text-red': 'light-dark(#cc0000, #ff7a7a)',
    '--color-background-teal': 'light-dark(#2e6b5a33, #5ab89833)',
    '--color-border-teal': 'light-dark(#2e6b5a, #5ab898)',
    '--color-icon-teal': 'light-dark(#2e6b5a, #5ab898)',
    '--color-text-teal': 'light-dark(#245546, #6ccaaa)',
    '--color-background-yellow': 'light-dark(#FFB60033, #ffc94033)',
    '--color-border-yellow': 'light-dark(#FFB600, #ffc940)',
    '--color-icon-yellow': 'light-dark(#FFB600, #ffc940)',
    '--color-text-yellow': 'light-dark(#cc9200, #ffd960)',
    '--spacing-0-5': '1px',
    '--spacing-1': '2px',
    '--spacing-1-5': '3px',
    '--spacing-2': '4px',
    '--spacing-3': '6px',
    '--spacing-4': '8px',
    '--spacing-5': '10px',
    '--spacing-6': '12px',
    '--spacing-7': '14px',
    '--spacing-8': '16px',
    '--spacing-9': '18px',
    '--spacing-10': '20px',
    '--spacing-11': '22px',
    '--spacing-12': '24px',
    '--radius-inner': '2px',
    '--radius-element': '4px',
    '--radius-container': '6px',
    '--radius-page': '14px',
    '--radius-chat': '14px',
    '--font-family-body': '"DM Sans", -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif',
    '--font-family-code': '"JetBrains Mono", "SF Mono", Monaco, Consolas, monospace',
    '--font-family-heading': '"Playwrite US Trad", Georgia, "Times New Roman", Times, serif',
    '--font-size-4xs': '0.4375rem',
    '--font-size-xs': '0.5625rem',
    '--font-size-sm': '0.6875rem',
    '--font-size-base': '0.75rem',
    '--font-size-lg': '0.875rem',
    '--font-size-xl': '0.9375rem',
    '--font-size-2xl': '1.0625rem',
    '--font-size-3xl': '1.1875rem',
    '--font-size-4xl': '1.375rem',
    '--font-size-5xl': '1.5rem',
    '--text-heading-1-leading': '1.4118',
    '--text-heading-2-leading': '1.6',
    '--text-heading-3-leading': '1.4286',
    '--text-heading-4-leading': '1.6667',
    '--text-heading-5-leading': '1.4545',
    '--text-heading-6-leading': '1.7778',
    '--text-body-leading': '1.6667',
    '--text-large-leading': '1.4286',
    '--text-label-leading': '1.6667',
    '--text-code-leading': '1.6667',
    '--text-supporting-leading': '1.4545',
    '--text-display-1-leading': '1.3333',
    '--text-display-2-leading': '1.4545',
    '--text-display-3-leading': '1.4737',
    '--size-element-sm': '26px',
    '--size-element-md': '28px',
    '--size-element-lg': '30px',
    '--shadow-low': '0 2px 4px #3E481D0D, 0 4px 8px #3E481D1A',
    '--shadow-med': '0 2px 4px #3E481D0D, 0 4px 12px #3E481D1A',
    '--shadow-high': '0 4px 6px #3E481D1A, 0 12px 24px #3E481D26',
    '--shadow-inset-hover': 'inset 0px 0px 0px 2px #3E481D30',
    '--shadow-inset-selected': 'inset 0px 0px 0px 2px #3E481D50',
    '--shadow-inset-success': 'inset 0px 0px 0px 2px #4D990050',
    '--shadow-inset-warning': 'inset 0px 0px 0px 2px #FFB60050',
    '--shadow-inset-error': 'inset 0px 0px 0px 2px #FD000050',
    '--duration-fast-min': '95ms',
    '--duration-fast': '125ms',
    '--duration-fast-max': '165ms',
    '--duration-medium-min': '225ms',
    '--duration-medium': '300ms',
    '--duration-medium-max': '400ms',
    '--duration-slow-min': '525ms',
    '--duration-slow': '700ms',
    '--duration-slow-max': '935ms',
    '--color-syntax-keyword': 'light-dark(#5a6b2a, #a8bf6a)',
    '--color-syntax-string': 'light-dark(#2e6b4a, #7bc49e)',
    '--color-syntax-comment': 'light-dark(#707E46, #707E46)',
    '--color-syntax-number': 'light-dark(#8c6b30, #d4b870)',
    '--color-syntax-function': 'light-dark(#3a5e8c, #7ba8d4)',
    '--color-syntax-type': 'light-dark(#6b4a8c, #b08ed4)',
    '--color-syntax-variable': 'light-dark(#3E481D, #C0CBA9)',
    '--color-syntax-operator': 'light-dark(#707E46, #94a468)',
    '--color-syntax-constant': 'light-dark(#8c6b30, #d4b870)',
    '--color-syntax-tag': 'light-dark(#8c3a3a, #d47a7a)',
    '--color-syntax-attribute': 'light-dark(#7c5e3a, #c4a882)',
    '--color-syntax-property': 'light-dark(#3a7c6b, #70c4b0)',
    '--color-syntax-punctuation': 'light-dark(#707E46, #5a6440)',
    '--color-syntax-background': 'light-dark(#F0F0E0, #1a1c14)',
  },
  components: {
    'heading': {
      'level:1': {
        'fontFamily': 'var(--font-family-heading)',
        'fontSize': 'var(--text-heading-1-size)',
        'fontWeight': 'var(--text-heading-1-weight)',
        'lineHeight': 'var(--text-heading-1-leading)',
      },
      'level:2': {
        'fontFamily': 'var(--font-family-heading)',
        'fontSize': 'var(--text-heading-2-size)',
        'fontWeight': 'var(--text-heading-2-weight)',
        'lineHeight': 'var(--text-heading-2-leading)',
      },
      'level:3': {
        'fontFamily': 'var(--font-family-heading)',
        'fontSize': 'var(--text-heading-3-size)',
        'fontWeight': 'var(--text-heading-3-weight)',
        'lineHeight': 'var(--text-heading-3-leading)',
      },
      'level:4': {
        'fontFamily': 'var(--font-family-heading)',
        'fontSize': 'var(--text-heading-4-size)',
        'fontWeight': 'var(--text-heading-4-weight)',
        'lineHeight': 'var(--text-heading-4-leading)',
      },
      'level:5': {
        'fontFamily': 'var(--font-family-heading)',
        'fontSize': 'var(--text-heading-5-size)',
        'fontWeight': 'var(--text-heading-5-weight)',
        'lineHeight': 'var(--text-heading-5-leading)',
      },
      'level:6': {
        'fontFamily': 'var(--font-family-heading)',
        'fontSize': 'var(--text-heading-6-size)',
        'fontWeight': 'var(--text-heading-6-weight)',
        'lineHeight': 'var(--text-heading-6-leading)',
      },
    },
    'text': {
      'type:body': {
        'fontFamily': 'var(--font-family-body)',
        'fontSize': 'var(--text-body-size)',
        'lineHeight': 'var(--text-body-leading)',
      },
      'type:large': {
        'fontFamily': 'var(--font-family-body)',
        'fontSize': 'var(--text-large-size)',
        'lineHeight': 'var(--text-large-leading)',
      },
      'type:label': {
        'fontFamily': 'var(--font-family-body)',
        'fontSize': 'var(--text-label-size)',
        'lineHeight': 'var(--text-label-leading)',
      },
      'type:code': {
        'fontFamily': 'var(--font-family-code)',
        'fontSize': 'var(--text-code-size)',
        'lineHeight': 'var(--text-code-leading)',
      },
      'type:supporting': {
        'fontFamily': 'var(--font-family-body)',
        'fontSize': 'var(--text-supporting-size)',
        'lineHeight': 'var(--text-supporting-leading)',
      },
      'type:display-1': {
        'fontFamily': 'var(--font-family-heading)',
        'fontSize': 'var(--text-display-1-size)',
        'lineHeight': 'var(--text-display-1-leading)',
      },
      'type:display-2': {
        'fontFamily': 'var(--font-family-heading)',
        'fontSize': 'var(--text-display-2-size)',
        'lineHeight': 'var(--text-display-2-leading)',
      },
      'type:display-3': {
        'fontFamily': 'var(--font-family-heading)',
        'fontSize': 'var(--text-display-3-size)',
        'lineHeight': 'var(--text-display-3-leading)',
      },
    },
    'button': {
      'base': {
        'borderRadius': 'var(--radius-full)',
      },
    },
    'card': {
      'base': {
        'borderRadius': 'var(--radius-page)',
        'padding': 'var(--spacing-3)',
      },
    },
    'section': {
      'base': {
        'padding': 'var(--spacing-3)',
      },
    },
  },
});